blank_issues_enabled: true
contact_links:
  - name: Slimefun Addon Community Discord Server
    url: https://discord.gg/SqD3gg5SAU
    about: You can ask stuff about FNAmplifications in the channel "#fnamplifications"
